Add options to hide icon, show speeds in bits or bytes, and show upload and download at the same time
noroadsleft000/gnome-network-stats pull request #32
Opened 2022-01-30 05:35 UTC by stringlapse

The settings to show the icon and use bytes are set by default to work the same as the previous behavior. I didn't update the screenshot in the readme because I only have one network interface so I can't show how multiple interfaces are supported. I saw showing upload and download at the same time was in TODO.md so I marked it off there.

2022-01-30 17:32 UTC, noroadsleft000 requested changes

2022-01-30 17:32 UTC, noroadsleft000 commented on utils/GenUtils.js
> +function bytesSpeedToString(amount, mode = appSettingsModel.displayBytes) {
Can you pass some hard coded value true.
This is reusable code, Idea is not to add model dependency on Utils.

2022-01-30 17:32 UTC, noroadsleft000 commented on prefs.js
> +            label: _(_("Show speeds in bytes instead of bits")),
you mistakenly called _() twice.

2022-01-30 17:32 UTC, noroadsleft000 commented on prefs.js
> +            label: _(_("Show icon in status bar (requires reload)")),
you mistakenly called _() twice.

2022-01-30 17:32 UTC, noroadsleft000 commented on utils/GenUtils.js
>   * @param {number} mode  0 - bits mode,  1 - bytes mode
Please change the type from` number -> boolean` in comments.

2022-03-07 15:51 UTC, noroadsleft000 commented
Seeing no activity on this for long time.
And, since there are some significant features added by the contributor.
We will go ahead with merging and address review comments in separate PR.

2022-03-07 15:51 UTC, merged

2022-03-15 21:25 UTC, stringlapse commented
Apologies, life got really busy for me. Thank you for fixing the problems and merging!